export const ADD_TO_CART = "ADD_TO_CART";
export const INCREASE_COUNT = "INCREASE_COUNT";
export const DECREASE_COUNT = "DECREASE_COUNT";
export const REMOVE_FROM_CART = "REMOVE_FROM_CART";
export const CLEAR_CART = "CLEAR_CART";
export const HANDLE_QUANTITY = "HANDLE_QUANTITY";
